name: "Feature Request"
description: "Request a feature you would see here."
title: "[Feature]: "
labels:
  - "feature"
  - "triage"
assignees:
  - "loicmaes"
body:
  - type: "markdown"
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: "input"
    id: "contact"
    attributes:
      label: "Contact Details"
      description: "How can we get in touch with you if we need more info?"
      placeholder: "ex. email@example.com"
    validations:
      required: false
  - type: "textarea"
    id: "feature-request"
    attributes:
      label: "What do you want?"
      description: "Also tell us, which new feature do you want?"
      placeholder: "Tell us what you want!"
    validations:
      required: true
